apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
      - name: mywebapp
        image: registry-1.docker.io/ercanuz/my-nodejs-app:1.2
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: datavolume
          mountPath: /data
        env:
        - name: DATABASE_HOST
          value: tcmbgwfkm.konsalt.info
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: contacts
        - name: DATABASE_USER
          value: postgres
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: password
      volumes:
      - name: datavolume
        persistentVolumeClaim:
          claimName: mywebdata