apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
spec:
  containers:
  - name: occlientdockerclient
    image: 's001elk2.konsalt.info:5555/jenkins-git-oc-agent-rhel8:1.1'
    securityContext:
      privileged: true
    command:
    - cat
    tty: true
  - name: dind
    image: s001elk2.konsalt.info:5555/mydockerdind:1.1
    securityContext:
      privileged: true
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
