apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
spec:
  containers:
  - name: occlientdockerclient
    image: 's001elk2.konsalt.info:5555/jenkins-git-oc-agent-rhel8:1.1'
    securityContext:
      privileged: true
    command:
    - cat
    tty: true
    volumeMounts:
      - name: workspace-volume
        mountPath: /home/jenkins/agent
  - name: dind
    image: s001elk2.konsalt.info:5555/mydockerdind:1.1
    securityContext:
      privileged: true
    volumeMounts:
      - name: workspace-volume
        mountPath: /home/jenkins/agent
      - name: dind-storage
        mountPath: /var/lib/docker
  - name: jnlp
    image: 'jenkins/inbound-agent:latest'
    args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
    volumeMounts:
      - name: workspace-volume
        mountPath: /home/jenkins/agent
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: workspace-volume
      persistentVolumeClaim:
        claimName: jenkinsnfspvc
