apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata: 
   name: kustomize-webapp-deploy
namespace: mywebapp   
resources:
  - ../../base/deployment-mywebapp.yaml
patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: mywebapp
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3