apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize-deployment-replica-production
namespace: mywebapp
resources:
  - ../../base/
patches:
  - target:
      kind: Deployment
      name: mywebapp
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3