apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data01/nfsdata/nfspv
    server: 192.168.1.195
  persistentVolumeReclaimPolicy: Retain
  storageClassName: thin-csi