kind: Deployment
apiVersion: apps/v1
metadata:
  name: mywebapp
  namespace: mywebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      restartPolicy: Always
      initContainers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: wait-for-db
          command:
            - sh
            - '-c'
            - >-
              until nc -zv $DATABASE_HOST $DATABASE_PORT; do echo 'Waiting for
              database to become available...'; sleep 1; done
          env:
            - name: DATABASE_HOST
              value: tcmbgwfkm.konsalt.info
            - name: DATABASE_PORT
              value: '5432'
          imagePullPolicy: Always
          volumeMounts:
            - name: env
              mountPath: /etc/config
          terminationMessagePolicy: File
          image: busybox
      imagePullSecrets:
        - name: registrypullsecret
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: mywebapp
          env:
            - name: DATABASE_HOST
              value: tcmbgwfkm.konsalt.info
            - name: DATABASE_PORT
              value: '5432'
            - name: DATABASE_NAME
              value: contacts
            - name: DATABASE_USER
              value: mywebapp
            - name: DATABASE_PASSWORD
              value: /etc/secret-volume/dbpassword
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: datavolume
              mountPath: /data
            - name: secret-volume
              mountPath: /etc/secret-volume
          terminationMessagePolicy: File
          image: 's001elk2.konsalt.info:5555/my-nodejs-app:2.0'
        - name: elastic-filebeat
          image: 's001elk2.konsalt.info:5555/filebeat:1.1'
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://s001elk1.konsalt.info:9200"
            - name: ELASTICSEARCH_USERNAME
              value: "elastic"
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mywebapp
                  key: elasticpassword
          command: ["filebeat", "-c", "/usr/share/filebeat/filebeat.yml"]
          volumeMounts:
            - name: datavolume
              mountPath: /data
        - name: fetch-secret
          image: s001elk2.konsalt.info:5555/dssfetchsecret:2.9
          command:
          - cat
          tty: true
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secret-volume
      volumes:
        - name: env
          emptyDir: {}
        - name: datavolume
          persistentVolumeClaim:
            claimName: mywebdata
        - name: secret-volume
          emptyDir: {}
