apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetch-secret-cronjob
spec:
  schedule: "* * * * *" # This schedule runs the job every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fetch-secret-mywebappdb
            image: s001elk2.konsalt.info:5555/dssfetchsecret:2.1
            imagePullPolicy: IfNotPresent
            env:
            - name: SECRET_SERVER_URL
              value: "https://pam.konsalt.info/SecretServer"
            - name: SECRET_ID
              value: "144"
            - name: USERNAME
              value: "admin"
            - name: PASSWORD
              value: "MesaKoz2023_"
            - name: DOMAIN
              value: "Local"
          restartPolicy: OnFailure
