apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hcpvaultsecretsapps-patch-role
  namespace: mywebapp
rules:
- apiGroups: ["secrets.hashicorp.com"]
  resources: ["hcpvaultsecretsapps"]
  verbs: ["patch"]