apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-mywebapp.yaml
  - mywebapp-service.yaml
  - mywebapp-route.yaml
  - mywebdata.pvc.yaml
  - registrypullsecret.yaml
  - create_mywebapp_secret_via_hcp.yaml
  - hashicorp-sp.yaml
  - hcpvaultsecretsapps-patch-role.yaml
  - hcpvaultsecretsapps-patch-rolebinding.yaml