apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mywebdata
  namespace: mywebapp
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
