apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mywebapp-db-password
  namespace: mywebapp
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: '144'
        metadataPolicy: None
        property: Password
      secretKey: dbpassword
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: konsalt-secret-server-cluster
  target:
    creationPolicy: Owner
    deletionPolicy: Retain