apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mywebapp-db-password
  namespace: mywebapp
  labels:
    app.kubernetes.io/instance: mywebapp
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: '144'
        metadataPolicy: None
        property: Password
      secretKey: dbpassword
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: konsalt-secret-server-cluster
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        dbpassword: '{{ .dbpassword }}'
        vault-secret-hash: '{{ .dbpassword | sha256sum }}'
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: '0'