apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
  namespace: mywebapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: mywebapp
  sessionAffinity: None
  type: ClusterIP
