apiVersion: v1
kind: ServiceAccount
metadata:
  name: cron-service-account
  namespace: mywebapp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-configmap-role
  namespace: mywebapp
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-configmap-rolebinding
  namespace: mywebapp
subjects:
- kind: ServiceAccount
  name: cron-service-account
  namespace: mywebapp
roleRef:
  kind: Role
  name: patch-configmap-role
  apiGroup: rbac.authorization.k8s.io