apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetch-secret-cron
spec:
  schedule: "*/1 * * * *"  # Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fetch-secret
            image: s001elk2.konsalt.info:5555/dssfetchsecret:6.2
            env:
              - name: SECRET_SERVER_URL
                value: "https://pam.konsalt.info/SecretServer"
              - name: SECRET_ID
                value: "144"
              - name: USERNAME
                value: "argocd"
              - name: PASSWORD
                value: "MesaKoz*2023"
              - name: DOMAIN
                value: "local"
            volumeMounts:
              - name: secret-volume
                mountPath: /etc/secret-volume
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: secret-volume
              emptyDir: {}
            - name: config-volume
              emptyDir: {}
          restartPolicy: OnFailure
