apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hcpvaultsecretsapps-patch-rolebinding
  namespace: mywebapp
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  kind: Role
  name: hcpvaultsecretsapps-patch-role
  apiGroup: rbac.authorization.k8s.io