apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Ortak kullanılacak Kubernetes manifestleri
resources:
  - create_mywebapp_secret_via_hcp.yaml
  - deployment-mywebapp.yaml
  - hashicorp-sp.yaml
  - hcpvaultsecretsapps-patch-role.yaml
  - hcpvaultsecretsapps-patch-rolebinding.yaml
  - mywebapp-route.yaml
  - mywebapp-service.yaml
  - mywebdata.pvc.yaml
  - registrypullsecret.yaml